<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>core_banking_lite</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.100.4" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />

		<PackageReference Include="Dapper" Version="2.1.66" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
	</ItemGroup>

</Project>
